---
title: "Get to Know Me"
author: "Brian Chavez"
date: 2021-05-09T21:13:14-05:00
categories: []
---

I am from Port Isabel, Texas, a small town on the southern Gulf Coast, where I graduated as valedictorian of Port Isabel High School. There, I founded the school’s first pre-medical organization, Future Health Careers Club, and was the president of the Student Body, National Honor Society, and Rotary Interact Club. I earned All-State Academic Elite Football Team Highest Honors and two State Championships in UIL Spelling and Vocabulary. 

At The University of Texas, I am majoring in Biology in the Health Science Scholars Honors Program with a minor in Kinesiology and Health Education. Outside of the classroom, I serve as the Health and Wellness Policy Director, working to address health issues that affect the student body. I work as an Undergraduate Researcher at Dell Children’s Medical Center in the Magnetoencephalography Lab, investigating the use of current presurgical motor mapping protocols. 

Beyond the curriculum, I have been blessed to have had amazing opportunities. From traveling to Israel to learn about one of the most historical and cultural regions in the world to volunteering in free medical clinics in the Dominican Republic, I have grown as an individual through my life experiences.

It is my ultimate goal to return to my medically-underserved region of South Texas to practice medicine. I hope to utilize my experiences and education to improve the lives of others.


